import Foundation
struct Challenge:Codable{let job_id:String;let point_id:String;let nonce:String;let expires_at:Double}
struct AttestationChallenge:Codable{let nonce:String;let expires_at:Double}
struct AttestationResponse:Codable{let trusted:Bool;let status:String;let key_id:String;let environment:String}
struct CaptureResponse:Codable{let evidence_id:String;let status:String;let photo_sha256:String;let note_sha256:String;let bind_hash:String;let written_at:String}
struct LocalLoginResponse:Codable{let access_token:String;let account_id:String;let role:String}
struct ShieldAPI{let base:URL;let token:String?
 func login(email:String,password:String)async throws->LocalLoginResponse{var r=URLRequest(url:base.appending(path:"/shield/auth/login"));r.httpMethod="POST";r.setValue("application/json",forHTTPHeaderField:"Content-Type");r.httpBody=try JSONSerialization.data(withJSONObject:["email":email,"password":password]);if let token{r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(d,x)=try await URLSession.shared.data(for:r);try ok(x);return try JSONDecoder().decode(LocalLoginResponse.self,from:d)}
 func attestationChallenge(accountID:String)async throws->AttestationChallenge{var r=URLRequest(url:base.appending(path:"/shield/attest/challenge"));r.httpMethod="POST";r.setValue("application/x-www-form-urlencoded",forHTTPHeaderField:"Content-Type");r.httpBody=Data("account_id=\(accountID.addingPercentEncoding(withAllowedCharacters:.urlQueryAllowed) ?? accountID)".utf8);if let token{r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(d,x)=try await URLSession.shared.data(for:r);try ok(x);return try JSONDecoder().decode(AttestationChallenge.self,from:d)}
 func registerAttestation(accountID:String,keyID:String,nonce:String,attestation:Data)async throws->AttestationResponse{var r=URLRequest(url:base.appending(path:"/shield/attest"));r.httpMethod="POST";let b="B\(UUID().uuidString)";r.setValue("multipart/form-data; boundary=\(b)",forHTTPHeaderField:"Content-Type");r.httpBody=fields([("account_id",accountID),("key_id",keyID),("nonce",nonce),("attestation",attestation.base64EncodedString())],b);if let token{r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(d,x)=try await URLSession.shared.data(for:r);try ok(x);return try JSONDecoder().decode(AttestationResponse.self,from:d)}
 func challenge(jobID:String,pointID:String,accountID:String)async throws->Challenge{var r=URLRequest(url:base.appending(path:"/shield/jobs/\(jobID)/challenge"));r.httpMethod="POST";let b="B\(UUID().uuidString)";r.setValue("multipart/form-data; boundary=\(b)",forHTTPHeaderField:"Content-Type");r.httpBody=fields([("point_id",pointID),("account_id",accountID)],b);if let token{r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(d,x)=try await URLSession.shared.data(for:r);try ok(x);return try JSONDecoder().decode(Challenge.self,from:d)}
 func capture(jobID:String,challenge:Challenge,accountID:String,photo:Data,locationStated:String,purpose:String,capturedAt:String,location:(Double,Double,Double)?,locationObservedAt:String?,mockFlag:Bool?,attestation:(String,Data)?)async throws->CaptureResponse{var f=[("point_id",challenge.point_id),("account_id",accountID),("nonce",challenge.nonce),("location_stated",locationStated),("purpose",purpose),("captured_at",capturedAt)];if let l=location{f += [("lat",String(l.0)),("lng",String(l.1)),("accuracy_m",String(l.2))]};if let observed=locationObservedAt{f.append(("location_observed_at",observed))};if let m=mockFlag{f.append(("mock_flag",String(m)))};if let a=attestation{f += [("attestation_key_id",a.0),("attestation_assertion",a.1.base64EncodedString())]};let b="B\(UUID().uuidString)";var body=fields(f,b);body += Data("--\(b)\r\nContent-Disposition: form-data; name=\"photo\"; filename=\"capture.jpg\"\r\nContent-Type: image/jpeg\r\n\r\n".utf8);body += photo;body += Data("\r\n--\(b)--\r\n".utf8);var r=URLRequest(url:base.appending(path:"/shield/jobs/\(jobID)/photos"));r.httpMethod="POST";r.setValue("multipart/form-data; boundary=\(b)",forHTTPHeaderField:"Content-Type");r.httpBody=body;if let token{r.setValue("Bearer \(token)",forHTTPHeaderField:"Authorization")};let(d,x)=try await URLSession.shared.data(for:r);try ok(x);return try JSONDecoder().decode(CaptureResponse.self,from:d)}
 private func fields(_ f:[(String,String)],_ b:String)->Data{f.reduce(into:Data()){o,i in o += Data("--\(b)\r\nContent-Disposition: form-data; name=\"\(i.0)\"\r\n\r\n\(i.1)\r\n".utf8)}};private func ok(_ x:URLResponse) throws{guard let h=x as? HTTPURLResponse,200..<300 ~= h.statusCode else{throw URLError(.badServerResponse)}}}
